import React from 'react'

// export const metadata = {
//   title: 'Blogs',
//   description: 'Generated by create next app',
// }

const Blogs = () => {
  return (
    <div>Blogs</div>
  )
}

export default Blogs